<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright 2016 Pavel Vechersky, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="ICARUS_2" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Global properties -->
  <xacro:property name="namespace" value="$(arg namespace)" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh" value="true" />
  <xacro:property name="yaml_path" value="$(arg yaml_path)"/>
  <xacro:property name="serial_device" value="$(arg serial_device)" />
  <xacro:property name="enable_wind" value="$(arg enable_wind)"/>

  <!-- Constants -->
  <xacro:property name="PI" value="3.1415926535897931" />

  <!-- Component masses -->
  <xacro:property name="mass_aileron" value="0.001" /> <!-- [kg] -->    <!-- !!! -->
  <xacro:property name="mass_elevator" value="0.00904" /> <!-- [kg] -->

  <!-- Aileron properties -->						<!-- !!! -->
  <xacro:property name="aileron_length" value="0.03" /> <!-- [m] -->
  <xacro:property name="aileron_width" value="0.15" /> <!-- [m] -->
  <xacro:property name="aileron_height" value="0.01" /> <!-- [m] -->
  <!-- <xacro:property name="aileron_min_angle" value="-0.349066" />  [rad] -->
  <!-- <xacro:property name="aileron_max_angle" value="0.349066" />  [rad]  -->
  <xacro:property name="aileron_color" value="Red" />
  <xacro:property name="aileron_left_mesh_file" value="package://rotors_description/meshes/techpod/techpod_aileron_left.dae" />
  <xacro:property name="aileron_right_mesh_file" value="package://rotors_description/meshes/techpod/techpod_aileron_right.dae" />

  <!-- Elevator properties -->
  <xacro:property name="elevator_length" value="0.08" /> <!-- [m] -->
  <xacro:property name="elevator_width" value="0.4" /> <!-- [m] -->
  <xacro:property name="elevator_height" value="0.005" /> <!-- [m] -->
  <!-- <xacro:property name="elevator_min_angle" value="-0.349066" /> [rad] -->
  <!-- <xacro:property name="elevator_max_angle" value="0.349066" /> [rad] -->
  <xacro:property name="elevator_color" value="Blue" />
  <xacro:property name="elevator_mesh_file" value="package://rotors_description/meshes/techpod/techpod_elevator.dae" />

  <!-- Inertia of the aileron, assuming it is a cuboid -->
  <xacro:property name="aileron_inertia">
    <xacro:box_inertia x="${aileron_length}" y="${aileron_width}" z="${aileron_height}" mass="${mass_aileron}" />
  </xacro:property>

  <!-- Inertia of the elevator, assuming it is a cuboid -->
  <xacro:property name="elevator_inertia">
    <xacro:box_inertia x="${elevator_length}" y="${elevator_width}" z="${elevator_height}" mass="${mass_elevator}" />
  </xacro:property>

  <!-- Servo PD controller paramters, tune after inertias of actuated links are set -->       <!-- !!! -->
  <xacro:property name="ctrl_surf_srv_params">
    <slew>3.3</slew>
    <p>0.0004</p>
    <d>0.00002</d>
  </xacro:property>
  <xacro:property name="tail_srv_params">
    <slew>3.3</slew>
    <p>0.05</p>
    <d>0.005</d>
  </xacro:property>
  <xacro:property name="wing_srv_params">
    <slew>0.52</slew>
    <p>5</p>
    <d>0</d>
  </xacro:property>

  <xacro:property name="ram_eff" value="0.5" />
  <xacro:property name="slip_eff" value="0.5" />
<xacro:property name="distance_origin_ground" value="0.0" />
  <xacro:property name="d_cg_x" value="0.01" /> <!-- FLU - I do not think we need this-->
  <xacro:property name="d_cg_z" value="0.04" /> <!-- FLU - I do not think we need this-->

  <!-- Included URDF Files -->						<!-- ??? -->
  <xacro:include filename="$(find rotors_description)/urdf/fixed_wing_X_base.xacro" />

  <!-- Fuselage -->
  <link name="${namespace}/base_link">
      <inertial>
        <mass value="0.8" />  
        <inertia ixx="0.0035" ixy="0.0" ixz="0.01" iyy="0.0082" iyz="0.0" izz="0.0045" />
        <origin xyz="0 0 0" rpy="0 0 0" />							<!-- Check Inertia -->
        <!-- <origin xyz="${0.19 + d_cg_x} 0 ${0.15 + d_cg_z}" rpy="0 0 0" />  -->
      </inertial>
      <visual>
        <origin xyz="0 0 ${distance_origin_ground}" rpy="${pi/2} 0 ${pi}" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Fuselage.stl" scale="0.001 0.001 0.001" /> 
        </geometry>
      </visual>
      <collision>
	<origin xyz="0 0 ${distance_origin_ground}" rpy="${pi/2} 0 ${pi}" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Fuselage.stl" scale="0.001 0.001 0.001" /> 
        </geometry>
      </collision>
  </link>
  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/White</material>
  </gazebo>
  <!-- <joint name="${namespace}/wheels_joint" type="fixed">
     <parent link="${namespace}/base_link" />
     <child link="${namespace}/wheels" />
  </joint>
  <link name="${namespace}/wheels">
     <inertial>
        <mass value="0.03" />
        <xacro:box_inertia x="0.07" y="0.025" z="0.07" mass="0.03" />
     </inertial>
     <collision>
       <origin xyz="0 0.200 0.07" rpy="0 0 0" /> 							<!- Origin is in the Middle of the .stl -
       <geometry>
         <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/wheels.stl" scale="0.001 0.001 0.001" /> <!- This is not implemented right now -
       </geometry>
     </collision>
     <visual>
        <geometry>
           <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/wheels.stl" scale="0.001 0.001 0.001" /> <!- This is not implemented right now -
        </geometry>
     </visual>
  </link>
  <gazebo reference="${namespace}/wheels">
     <material>Gazebo/Grey</material>
  </gazebo> -->

  <!-- Wing -->
  <joint name="${namespace}/wing_left_joint" type="revolute">
    <origin xyz="0 0.060 ${distance_origin_ground}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <parent link="${namespace}/base_link" />
    <child link="${namespace}/wing_left" />
    <!--<limit upper="0" lower="0" effort="10" velocity="20"/>-->
    <limit upper="-0.15" lower="-1.57" effort="10" velocity="20"/>  <!-- !!! -->
    <dynamics damping="0.5" friction="0" />  <!-- !!! -->
  </joint>
  <link name="${namespace}/wing_left">
      <inertial>
        <mass value="0.300" /> <!-- Why was it 0.001 before? -->
        <inertia ixx="0.0273" ixy="0.0" ixz="0.0002" iyy="0.0009" iyz="0.0" izz="0.0278" /> <!-- I left this one as it was -->
        <!--<origin xyz="0.0287 0 -0.035" rpy="0 0 0" />-->
        <origin xyz="0 0 0" rpy="0 0 0" />                      <!-- Check Inertia -->
      </inertial>
      <visual>
        <origin xyz="0 0.500 0" rpy="${pi/2} 0 ${pi}" />              <!-- Origin is in the Middle of the .stl -->
        <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Wing.stl" scale="0.001 0.001 0.001" /> 
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0.500 0" rpy="${pi/2} 0 ${pi}" />              <!-- Origin is in the Middle of the .stl -->
        <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Wing.stl" scale="0.001 0.001 0.001" /> 
        </geometry>
      </collision>
  </link>
  <gazebo reference="${namespace}/wing_left">
    <material>Gazebo/White</material>
  </gazebo>

 <joint name="${namespace}/wing_right_joint" type="revolute">
    <origin xyz="0 -0.060 ${distance_origin_ground}" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <parent link="${namespace}/base_link" />
    <child link="${namespace}/wing_right" />
    <!--<limit upper="0" lower="0" effort="10" velocity="20"/>-->
    <limit upper="-0.15" lower="-1.57" effort="10" velocity="20"/>  <!-- !!! -->
    <dynamics damping="0.5" friction="0" />  <!-- !!! -->
  </joint>
  <link name="${namespace}/wing_right">
      <inertial>
        <mass value="0.300" /> <!-- Why was it 0.001 before? -->
        <inertia ixx="0.0273" ixy="0.0" ixz="0.0002" iyy="0.0009" iyz="0.0" izz="0.0278" /> <!-- I left this one as it was -->
        <!--<origin xyz="0.0287 0 -0.035" rpy="0 0 0" />-->
        <origin xyz="0 0 0" rpy="0 0 0" />                      <!-- Check Inertia -->
      </inertial>
      <visual>
        <origin xyz="0 0.060 0" rpy="${pi/2} 0 ${pi}" />              <!-- Origin is in the Middle of the .stl -->
        <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Wing.stl" scale="0.001 0.001 0.001" /> 
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0.060 0" rpy="${pi/2} 0 ${pi}" />              <!-- Origin is in the Middle of the .stl -->
        <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Wing.stl" scale="0.001 0.001 0.001" /> 
        </geometry>
      </collision>
  </link>
  <gazebo reference="${namespace}/wing_right">
    <material>Gazebo/White</material>
  </gazebo>

  <!-- <joint name="${namespace}/front_motors_joint" type="fixed">
     <parent link="${namespace}/wing_left" />
     <child link="${namespace}/front_motors" />
  </joint>
  <link name="${namespace}/front_motors">  <!- How are all front motors placed? -
     <inertial>
        <mass value="0.280" />
        <xacro:box_inertia x="0.032" y="0.028" z="0.028" mass="0.280" />
     </inertial>
     <visual>
        <origin xyz="-0.20 0 -0.2095" rpy="0 0 0" />             <!- !!! Where to place them !!! -
        <geometry>
           <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Motor.stl" scale="0.01 0.01 0.01" /> <!- Several of them? or attached to wing? -
        </geometry>
     </visual>
  </link>
  <gazebo reference="${namespace}/front_motors">
     <material>Gazebo/Grey</material>
  </gazebo> -->

  <!-- Ailerons -->
  <joint name="${namespace}/aileron_left_joint" type="revolute">
    <origin xyz="-0.074 0.355 -0.007" rpy="0 0 0" />             <!-- !!! -->
    <axis xyz="0 -1 0" />
    <parent link="${namespace}/wing_left" />
    <child link="${namespace}/aileron_left" />
    <limit upper="0.53" lower="-0.53" effort="10" velocity="20"/>  <!-- !!! -->
  </joint>
  <link name="${namespace}/aileron_left">
    <inertial>
      <mass value="${mass_aileron}" />
      <xacro:insert_block name="aileron_inertia" />
    </inertial>
    <visual>
      <origin xyz="0.075 -0.410 0" rpy="${pi/2} 0 ${pi}" />           <!-- !!! -->
      <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Aileron.stl" scale="0.001 0.001 0.001" /> 
      </geometry>
    </visual>
  </link>
  <gazebo reference="${namespace}/aileron_left">
    <material>Gazebo/${aileron_color}</material>
  </gazebo>

  <joint name="${namespace}/aileron_right_joint" type="revolute">
    <origin xyz="-0.074 -0.355 -0.007" rpy="0 0 0" />            <!-- !!! -->
    <axis xyz="0 -1 0" />
    <parent link="${namespace}/wing_right" />
    <child link="${namespace}/aileron_right" />
    <limit upper="0.53" lower="-0.53" effort="10" velocity="20"/> <!-- !!! -->
  </joint>
  <link name="${namespace}/aileron_right">
    <inertial>
      <mass value="${mass_aileron}" />
      <xacro:insert_block name="aileron_inertia" />
    </inertial>
    <visual>
      <origin xyz="0.075 -0.395 0" rpy="${pi/2} 0 ${pi}" />            <!-- !!! -->
      <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Aileron.stl" scale="0.001 0.001 0.001" /> 
      </geometry>
    </visual>
  </link>
  <gazebo reference="${namespace}/aileron_right">
    <material>Gazebo/${aileron_color}</material>
  </gazebo>

  <!-- Elevator -->
  <joint name="${namespace}/elevator_joint" type="revolute">
    <origin xyz="-0.465 0 -0.0115" rpy="0 0 0" />                 
    <axis xyz="0 -1 0" />
    <parent link="${namespace}/base_link" />
    <child link="${namespace}/elevator" />
    <limit upper="0.53" lower="-0" effort="10" velocity="20"/> <!-- !!! -->
  </joint>
  <link name="${namespace}/elevator">
    <inertial>
      <mass value="${mass_elevator}" />
      <xacro:insert_block name="elevator_inertia" />
    </inertial>
    <visual>
      <origin xyz="0.464 0 0.0123" rpy="${pi/2} 0 ${pi}" />               <!-- Origin is in the Middle of the .stl -->
      <geometry>
          <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Elevator.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>
  <gazebo reference="${namespace}/elevator">
    <material>Gazebo/${elevator_color}</material>
  </gazebo>

  <!-- Back Motors -->
  <!-- <joint name="${namespace}/back_motors_joint" type="fixed">
     <parent link="${namespace}/elevator" />
     <child link="${namespace}/back_motors" />
  </joint>
  <link name="${namespace}/back_motors">
     <inertial>
        <mass value="0.180" />
        <xacro:box_inertia x="0.018" y="0.025" z="0.025" mass="0.180" />
     </inertial>                                            <!- Check inertia -
     <visual>
        <origin xyz="-0.20 0 -0.2095" rpy="0 0 0" />             <!- !!! Where to place them !!! -
        <geometry>
           <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/Motor.stl" scale="0.01 0.01 0.01" /> <!- Several or attached? -
        </geometry>
     </visual>
  </link>
  <gazebo reference="${namespace}/front_motors">
     <material>Gazebo/Grey</material>
  </gazebo> -->

  <!-- Propellers -->
  <joint name="${namespace}/propeller_front_left_joint" type="continuous">
    <origin xyz="0.125 0.225 -0.04" rpy="0 0 0" />      <!-- !!! -->
    <axis xyz="1 0 0" />
    <parent link="${namespace}/wing_left" />
    <child link="${namespace}/propeller_front_left" />
  </joint>
  <link name="${namespace}/propeller_front_left">
    <inertial>
      <mass value="0.0125" />                                    <!-- !!! -->
      <xacro:cylinder_inertia r="0.14" h="0.02" mass="0.0125" />
    </inertial>
    <visual>
      <origin xyz="0 0 -0.015" rpy="0 ${0.45*pi} 0" />                    <!-- !!! -->
      <geometry>
        <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/iris_prop_cw.dae" scale="0.9 0.9 0.9"/> <!--This needs to be replace with our mesh -->
      </geometry>
    </visual>
  </link>
  <gazebo reference="${namespace}/propeller_front_left">
    <material>Gazebo/White</material>
  </gazebo>

  <joint name="${namespace}/propeller_fron_right_joint" type="continuous">
    <origin xyz="0.125 -0.225 -0.04" rpy="0 0 0" />     <!-- !!! -->
    <axis xyz="1 0 0" />
    <parent link="${namespace}/wing_right" />
    <child link="${namespace}/propeller_front_right" />
  </joint>
  <link name="${namespace}/propeller_front_right">
    <inertial>
      <mass value="0.0125" />                                    <!-- !!! -->
      <xacro:cylinder_inertia r="0.14" h="0.02" mass="0.0125" /> 
    </inertial>
    <visual>
      <origin xyz="0.0035 0 -0.015" rpy="0 ${0.45*pi} 0" />               <!-- !!! -->
      <geometry>
        <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/iris_prop_ccw.dae" scale="0.9 0.9 0.9"/> <!--This needs to be replace with our mesh -->
      </geometry>
    </visual>
  </link>
  <gazebo reference="${namespace}/propeller_front_right">
    <material>Gazebo/LightGrey</material>
  </gazebo>

  <joint name="${namespace}/propeller_back_left_joint" type="continuous">
    <origin xyz="0 0.185 0.04" rpy="0 0 0" />                    <!-- !!! -->
    <axis xyz="0 0 1" />
    <parent link="${namespace}/elevator" />
    <child link="${namespace}/propeller_back_left" />
  </joint>
  <link name="${namespace}/propeller_back_left">
    <inertial>
      <mass value="0.005" />                                     <!-- !!! -->
      <xacro:cylinder_inertia r="0.08" h="0.01" mass="0.005" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />                    <!-- !!! -->
      <geometry>
        <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/iris_prop_ccw.dae" scale="0.6 0.6 0.6"/> 
      </geometry>
    </visual>
  </link>
  <gazebo reference="${namespace}/propeller_back_left">
    <material>Gazebo/Orange</material>
  </gazebo>

  <joint name="${namespace}/propeller_back_right_joint" type="continuous">
    <origin xyz="0 -0.185 0.04" rpy="0 0 0" />                   <!-- !!! -->
    <axis xyz="0 0 1" />
    <parent link="${namespace}/elevator" />
    <child link="${namespace}/propeller_back_right" />
  </joint>
  <link name="${namespace}/propeller_back_right">
    <inertial>
      <mass value="0.005" />                                    <!-- !!! -->
      <xacro:cylinder_inertia r="0.08" h="0.01" mass="0.005" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />                   <!-- !!! -->
      <geometry>
        <mesh filename="package://rotors_description/meshes/IGNIS/ICARUS_2/iris_prop_ccw.dae" scale="0.6 0.6 0.6"/> 
      </geometry>
    </visual>
  </link>
  <gazebo reference="${namespace}/propeller_back_right">
    <material>Gazebo/Orange</material>
  </gazebo>

  <xacro:if value="${enable_wind}">
    <gazebo>
      <plugin filename="librotors_gazebo_wind_beta_plugin.so" name="wind_beta_plugin">
        <robotNamespace>${namespace}</robotNamespace>
        <windLayer>
          <layer name="layer1">
            <altitude>10</altitude>
            <windMeanNED>-2 0 0</windMeanNED>
          </layer>
          <layer name="layer2">
            <altitude>25</altitude>
            <windMeanNED>-3 0 0</windMeanNED>
          </layer>
          <layer name="layer3">
            <altitude>35</altitude>
            <windMeanNED>-10 0 0</windMeanNED>
          </layer>
        </windLayer>
        <findWind>
          <query name="q1">
            <linkName>${namespace}/base_link</linkName>
            <windTopic>wind_base_link</windTopic>
          </query>
        </findWind>
        <lambdaMin>10</lambdaMin>
        <lengthScale>725</lengthScale>
        <fourierNNN>7 7 7</fourierNNN>
        <sigma>2</sigma>
        <trnspVelTurbNED>5 0 0</trnspVelTurbNED>
      </plugin>
    </gazebo>
  </xacro:if>

<!-- Gazebo files. There are missing .yaml files -->
<!-- need to change parameter -->
  <gazebo>
    <plugin filename="librotors_gazebo_propulsion_plugin.so" name="propulsion_plugin">
      <robotNamespace>${namespace}</robotNamespace>
      <prop name="propeller_front_left">
        <linkNameRef>${namespace}/wing_left</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <cp>0.125 0.225 -0.038</cp>			<!-- !!! -->
        <axisPosRot>-0.9877 0 -0.1564</axisPosRot>
        <turnDir>cw</turnDir>
        <speedRefTopic>propeller_front_left_ref</speedRefTopic>
        <propParamsYAML>${yaml_path}/cl84b_main_prop.yaml</propParamsYAML> <!-- Missing -->
        <tauUp>0.075</tauUp>
        <tauDown>0.15</tauDown>
        <rdpsMax>1010</rdpsMax>
        <slpstrTopic>propeller_front_left_slpstr</slpstrTopic>
        <ramEff>${ram_eff}</ramEff>
        <visTopic>propeller_front_left_vis</visTopic>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
      </prop>
      <prop name="propeller_front_right">
        <linkNameRef>${namespace}/wing_right</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <cp>0.125 -0.225 -0.038</cp>
        <axisPosRot>0.9877 0 0.1564</axisPosRot>
        <turnDir>ccw</turnDir>
        <speedRefTopic>propeller_front_right_ref</speedRefTopic>
        <propParamsYAML>${yaml_path}/cl84b_main_prop.yaml</propParamsYAML> <!-- Missing -->
        <tauUp>0.075</tauUp>
        <tauDown>0.15</tauDown>
        <rdpsMax>1010</rdpsMax>
        <slpstrTopic>propeller_front_right_slpstr</slpstrTopic>
        <ramEff>${ram_eff}</ramEff>
        <visTopic>propeller_front_right_vis</visTopic>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
      </prop>
      <prop name="propeller_back_left">
        <linkNameRef>${namespace}/elevator</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <cp>-0.03 0 0.04</cp>
        <axisPosRot>0 0 1</axisPosRot>
        <turnDir>ccw</turnDir>
        <speedRefTopic>propeller_back_left_ref</speedRefTopic>
        <propParamsYAML>${yaml_path}/cl84b_tail_prop.yaml</propParamsYAML> <!-- Missing -->
        <tauUp>0.05</tauUp>
        <tauDown>0.1</tauDown>
        <rdpsMax>1410</rdpsMax>
        <slpstrTopic>propeller_back_left_slpstr</slpstrTopic>
        <visTopic>propeller_back_left_vis</visTopic>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
      </prop>
      <prop name="propeller_back_right">
        <linkNameRef>${namespace}/elevator</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <cp>-0.03 0 0.04</cp>
        <axisPosRot>0 0 1</axisPosRot>
        <turnDir>ccw</turnDir>
        <speedRefTopic>propeller_back_right_ref</speedRefTopic>
        <propParamsYAML>${yaml_path}/cl84b_tail_prop.yaml</propParamsYAML> <!-- Missing -->
        <tauUp>0.05</tauUp>
        <tauDown>0.1</tauDown>
        <rdpsMax>1410</rdpsMax>
        <slpstrTopic>propeller_back_right_slpstr</slpstrTopic>
        <visTopic>propeller_back_right_vis</visTopic>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
      </prop>
    </plugin>
  </gazebo>

  <gazebo> 
    <plugin filename="librotors_gazebo_aerodynamics_plugin.so" name="aerodynamics_plugin">
      <robotNamespace>${namespace}</robotNamespace>
      <linkName>${namespace}/base_link</linkName>
      <aeroForcesVis>aero_force_vis_0</aeroForcesVis>
      <body>
        <element>
          <!--<aBdyXX>0.0225</aBdyXX>
          <aBdyYY>0.12</aBdyYY>
          <aBdyZZ>0.12</aBdyZZ>-->
          <aBdyXX>0.01125</aBdyXX>
          <aBdyYY>0</aBdyYY>
          <aBdyZZ>0</aBdyZZ>
          <forward>1 0 0</forward>
          <upward>0 0 1</upward>
          <cp>0.18 0.0 0.15</cp>
          <wind name="wind">
            <topic>wind_base_link</topic>
          </wind>
        </element>
      </body>
      <airfoil>
        <segment name="elevator">
          <forward>1 0 0</forward>
          <upward>0 0 1</upward>
          <cp>-0.27 0.1 0.15</cp>
          <seg_area>0.0175</seg_area>
          <seg_chord>0.12</seg_chord>
          <aeroParamsYAML>${yaml_path}/cl84b_tail_airfoil.yaml</aeroParamsYAML>
          <wind name="wind">
            <topic>wind_base_link</topic>
          </wind>
          <control>
            <cs name="elevator">
                <controlJoint>${namespace}/elevator_joint</controlJoint>
                <radToCLift>2</radToCLift>
                <radToCDrag>0.0</radToCDrag>
                <radToCPitch>0.0</radToCPitch>
            </cs>
          </control>
	</segment>
      </airfoil>
    </plugin>
  </gazebo>

<!-- Aerodynamics of surface areas and stuff (needs to adapted to our system) -->
  <gazebo>
    <plugin filename="librotors_gazebo_aerodynamics_plugin.so" name="aerodynamics_plugin">
      <robotNamespace>${namespace}</robotNamespace>
      <aeroForcesVis>aero_force_vis_1</aeroForcesVis>
      <airfoil>
      <segment name="WL1">
        <linkNameRef>${namespace}/wing_left</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 0.072 -0.005</cp>
        <seg_area>0.004</seg_area>
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
      </segment>
      <segment name="WL2">
        <linkNameRef>${namespace}/wing_left</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 0.145 -0.005</cp> <!-- Different from above -->
        <seg_area>0.0195</seg_area> <!-- Different from above -->
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
        <indVel name="propeller_front_left">
           <topic>propeller_front_left_slpstr</topic>
           <eff>${slip_eff}</eff>
        </indVel>
      </segment>
      <segment name="WL3">
        <linkNameRef>${namespace}/wing_left</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 0.310 -0.005</cp>
        <seg_area>0.0195</seg_area>
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <control>
          <cs name="aileron_left">
              <controlJoint>${namespace}/aileron_left_joint</controlJoint>
              <radToCLift>2</radToCLift>
              <radToCDrag>0.0</radToCDrag>
              <radToCPitch>0.0</radToCPitch>
          </cs>
        </control>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
        <indVel name="propeller_front_left">
           <topic>propeller_front_left_slpstr</topic>
           <eff>${slip_eff}</eff>
        </indVel>
      </segment>
      <segment name="WL4">
        <linkNameRef>${namespace}/wing_left</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 0.420 -0.005</cp>
        <seg_area>0.0175</seg_area>
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
        <control>
          <cs name="aileron_left">
              <controlJoint>${namespace}/aileron_left_joint</controlJoint>
              <radToCLift>2</radToCLift>
              <radToCDrag>0.0</radToCDrag>
              <radToCPitch>0.0</radToCPitch>
          </cs>
        </control>
      </segment>
      <segment name="WR1">
        <linkNameRef>${namespace}/wing_right</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 -0.072 -0.005</cp>
        <seg_area>0.004</seg_area>
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
      </segment>
      <segment name="WR2">
        <linkNameRef>${namespace}/wing_right</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 -0.145 -0.005</cp>
        <seg_area>0.0195</seg_area>
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
        <indVel name="propeller_front_right">
           <topic>propeller_front_right_slpstr</topic>
           <eff>${slip_eff}</eff>
        </indVel>
      </segment>
      <segment name="WR3">
        <linkNameRef>${namespace}/wing_right</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 -0.310 -0.005</cp>
        <seg_area>0.0195</seg_area>
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <control>
          <cs name="aileron_right">
              <controlJoint>${namespace}/aileron_right_joint</controlJoint>
              <radToCLift>2</radToCLift>
              <radToCDrag>0.0</radToCDrag>
              <radToCPitch>0.0</radToCPitch>
          </cs>
        </control>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
        <indVel name="propeller_front_right">
           <topic>propeller_front_right_slpstr</topic>
           <eff>${slip_eff}</eff>
        </indVel>
      </segment>
      <segment name="WR4">
        <linkNameRef>${namespace}/wing_right</linkNameRef>
        <linkNameAct>${namespace}/base_link</linkNameAct>
        <forward>1 0 0</forward>
        <upward>0 0 1</upward>
        <cp>0.01 -0.420 -0.005</cp>
        <seg_area>0.0175</seg_area>
        <seg_chord>0.16</seg_chord>
        <aeroParamsYAML>${yaml_path}/cl84b_wing_airfoil.yaml</aeroParamsYAML>
        <wind name="wind">
          <topic>wind_base_link</topic>
        </wind>
        <control>
          <cs name="aileron_right">
              <controlJoint>${namespace}/aileron_right_joint</controlJoint>
              <radToCLift>2</radToCLift>
              <radToCDrag>0.0</radToCDrag>
              <radToCPitch>0.0</radToCPitch>
          </cs>
        </control>
      </segment>
      </airfoil>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin filename="librotors_gazebo_mavlink_interface.so" name="gazebo_mavlink_interface">
      <robotNamespace>${namespace}</robotNamespace>
      <protocol_version>2.0</protocol_version>
      <imuSubTopic>/imu</imuSubTopic>
      <imu_rate>250</imu_rate>
      <gpsSubTopic>/gps</gpsSubTopic>
      <gpsGtSubTopic>/gps_gt</gpsGtSubTopic>
      <lidarSubTopic>/lidar_lite_v3</lidarSubTopic>
      <opticalFlowSubTopic></opticalFlowSubTopic>
      <mavlink_addr>INADDR_ANY</mavlink_addr>
      <mavlink_udp_port>14560</mavlink_udp_port>
      <serialEnabled>true</serialEnabled>
      <serialDevice>${serial_device}</serialDevice>
      <baudRate>921600</baudRate>
      <qgc_addr>INADDR_ANY</qgc_addr>
      <qgc_udp_port>14550</qgc_udp_port>
      <hil_mode>true</hil_mode>
      <hil_state_level>true</hil_state_level>
      <enable_lockstep>false</enable_lockstep>
      <use_tcp>false</use_tcp>
      <motorSpeedCommandPubTopic>/command/motor_speed_old</motorSpeedCommandPubTopic>
      <actuatorsPubTopic>/command/motor_speed</actuatorsPubTopic>
      <linkName>${namespace}/base_link</linkName> <!-- reference link frame for airspeed and baro alt-->
      <pitotPos>0 0 0</pitotPos>           <!-- pitot position wrt reference link -->
      <baroPos>0 0 0</baroPos>            <!-- baro position wrt reference link -->
      <wind name="wind">                          <!-- include wind in airspeed measurement -->
        <topic>wind_base_link</topic>
      </wind>
      <control_channels>
      <channel name="propeller_front_left">
        <input_index>0</input_index>
        <input_offset>1</input_offset>
        <input_scaling>505</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>gz_msg</joint_control_type>
        <gztopic>propeller_front_left_ref</gztopic>
      </channel>
      <channel name="propeller_front_left_anim">
         <input_index>0</input_index>
         <input_offset>1</input_offset>
         <input_scaling>20</input_scaling>
         <zero_position_disarmed>0</zero_position_disarmed>
         <zero_position_armed>0</zero_position_armed>
         <joint_control_type>velocity</joint_control_type>
         <joint_name>${namespace}/propeller_front_left_joint</joint_name>
      </channel>
      <channel name="propeller_front_right">
        <input_index>1</input_index>
        <input_offset>1</input_offset>
        <input_scaling>505</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>gz_msg</joint_control_type>
        <gztopic>propeller_front_right_ref</gztopic>
      </channel>
      <channel name="propeller_front_right_anim">
         <input_index>1</input_index>
         <input_offset>1</input_offset>
         <input_scaling>20</input_scaling>
         <zero_position_disarmed>0</zero_position_disarmed>
         <zero_position_armed>0</zero_position_armed>
         <joint_control_type>velocity</joint_control_type>
         <joint_name>${namespace}/propeller_front_right_joint</joint_name>
      </channel>
      <channel name="propeller_back_left">
        <input_index>2</input_index>
        <input_offset>1</input_offset>
        <input_scaling>705</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>gz_msg</joint_control_type>
        <gztopic>propeller_back_left_ref</gztopic>
      </channel>
      <channel name="propeller_back_left_anim">
         <input_index>2</input_index>
         <input_offset>1</input_offset>
         <input_scaling>20</input_scaling>
         <zero_position_disarmed>0</zero_position_disarmed>
         <zero_position_armed>0</zero_position_armed>
         <joint_control_type>velocity</joint_control_type>
         <joint_name>${namespace}/propeller_back_left_joint</joint_name>
      </channel>
      <channel name="propeller_back_right">
        <input_index>2</input_index>
        <input_offset>1</input_offset>
        <input_scaling>705</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>gz_msg</joint_control_type>
        <gztopic>propeller_back_right_ref</gztopic>
      </channel>
      <channel name="propeller_back_right_anim">
         <input_index>2</input_index>
         <input_offset>1</input_offset>
         <input_scaling>20</input_scaling>
         <zero_position_disarmed>0</zero_position_disarmed>
         <zero_position_armed>0</zero_position_armed>
         <joint_control_type>velocity</joint_control_type>
         <joint_name>${namespace}/propeller_back_right_joint</joint_name>
      </channel>
      <channel name="aileron_left">
        <input_index>4</input_index>
        <input_offset>0</input_offset>
        <input_scaling>0.53</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>servo</joint_control_type>
        <servo_params>
          <xacro:insert_block name="ctrl_surf_srv_params" />
        </servo_params>
        <joint_name>${namespace}/aileron_left_joint</joint_name>
        <gztopic>aileron_left_pos</gztopic>
      </channel>
      <channel name="aileron_right">
        <input_index>5</input_index>
        <input_offset>0</input_offset>
        <input_scaling>-0.53</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>servo</joint_control_type>
        <servo_params>
          <xacro:insert_block name="ctrl_surf_srv_params" />
        </servo_params>
        <joint_name>${namespace}/aileron_right_joint</joint_name>
        <gztopic>aileron_right_pos</gztopic>
      </channel>
      <channel name="elevator">
        <input_index>6</input_index>
        <input_offset>0</input_offset>
        <input_scaling>-0.53</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>servo</joint_control_type>
        <servo_params>
          <xacro:insert_block name="ctrl_surf_srv_params" />
        </servo_params>
        <joint_name>${namespace}/elevator_joint</joint_name>
      </channel>
      <channel name="tail"> <!-- I do not know if we need this in our Drone -->
        <input_index>8</input_index>
        <input_offset>0</input_offset>
        <input_scaling>0.53</input_scaling>
        <zero_position_disarmed>0</zero_position_disarmed>
        <zero_position_armed>0</zero_position_armed>
        <joint_control_type>servo</joint_control_type>
        <servo_params>
          <xacro:insert_block name="tail_srv_params" />
        </servo_params>
        <joint_name>${namespace}/tail_thruster_joint</joint_name>
      </channel>
      <channel name="wing_left">
         <input_index>3</input_index>
         <input_offset>0</input_offset>
         <input_scaling>-1.57</input_scaling>
         <zero_position_disarmed>0</zero_position_disarmed>
         <zero_position_armed>0</zero_position_armed>
         <joint_control_type>servo</joint_control_type>
         <servo_params>
           <xacro:insert_block name="wing_srv_params" />
         </servo_params>
         <joint_name>${namespace}/wing_left_joint</joint_name>
      </channel><!-- These have to go to the same servo -->
      <channel name="wing_right">
         <input_index>3</input_index>
         <input_offset>0</input_offset>
         <input_scaling>-1.57</input_scaling>
         <zero_position_disarmed>0</zero_position_disarmed>
         <zero_position_armed>0</zero_position_armed>
         <joint_control_type>servo</joint_control_type>
         <servo_params>
           <xacro:insert_block name="wing_srv_params" />
         </servo_params>
         <joint_name>${namespace}/wing_right_joint</joint_name>
      </channel><!-- These have to go to the same servo -->
    </control_channels>
  </plugin>
  </gazebo>


</robot>
